[target.x86_64-unknown-linux-gnu]
linker = "clang"
rustflags = ["-C", "link-arg=-fuse-ld=/usr/bin/mold"]

[target.x86_64-pc-windows-msvc]
linker = "lld"
rustflags = [
  "-Lnative=/home/finns/.xwin/crt/lib/x86_64",
  "-Lnative=/home/finns/.xwin/sdk/lib/um/x86_64",
  "-Lnative=/home/finns/.xwin/sdk/lib/ucrt/x86_64"
]
